// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Regenerate bindings with `flutter pub run ffigen --config plugins/ffi/jolt.ffigen.yaml`.
///
class Jolt {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Jolt(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Jolt.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// \mainpage Dynamically Linked Dart API
  ///
  /// This exposes a subset of symbols from dart_api.h and dart_native_api.h
  /// available in every Dart embedder through dynamic linking.
  ///
  /// All symbols are postfixed with _DL to indicate that they are dynamically
  /// linked and to prevent conflicts with the original symbol.
  ///
  /// Link `dart_api_dl.c` file into your library and invoke
  /// `Dart_InitializeApiDL` with `NativeApi.initializeApiDLData`.
  ///
  /// Returns 0 on success.
  int Dart_InitializeApiDL(
    ffi.Pointer<ffi.Void> data,
  ) {
    return _Dart_InitializeApiDL(
      data,
    );
  }

  late final _Dart_InitializeApiDLPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'Dart_InitializeApiDL');
  late final _Dart_InitializeApiDL = _Dart_InitializeApiDLPtr.asFunction<
      int Function(ffi.Pointer<ffi.Void>)>();

  late final ffi.Pointer<Dart_PostCObject_Type> _Dart_PostCObject_DL =
      _lookup<Dart_PostCObject_Type>('Dart_PostCObject_DL');

  Dart_PostCObject_Type get Dart_PostCObject_DL => _Dart_PostCObject_DL.value;

  set Dart_PostCObject_DL(Dart_PostCObject_Type value) =>
      _Dart_PostCObject_DL.value = value;

  late final ffi.Pointer<Dart_PostInteger_Type> _Dart_PostInteger_DL =
      _lookup<Dart_PostInteger_Type>('Dart_PostInteger_DL');

  Dart_PostInteger_Type get Dart_PostInteger_DL => _Dart_PostInteger_DL.value;

  set Dart_PostInteger_DL(Dart_PostInteger_Type value) =>
      _Dart_PostInteger_DL.value = value;

  late final ffi.Pointer<Dart_NewNativePort_Type> _Dart_NewNativePort_DL =
      _lookup<Dart_NewNativePort_Type>('Dart_NewNativePort_DL');

  Dart_NewNativePort_Type get Dart_NewNativePort_DL =>
      _Dart_NewNativePort_DL.value;

  set Dart_NewNativePort_DL(Dart_NewNativePort_Type value) =>
      _Dart_NewNativePort_DL.value = value;

  late final ffi.Pointer<Dart_CloseNativePort_Type> _Dart_CloseNativePort_DL =
      _lookup<Dart_CloseNativePort_Type>('Dart_CloseNativePort_DL');

  Dart_CloseNativePort_Type get Dart_CloseNativePort_DL =>
      _Dart_CloseNativePort_DL.value;

  set Dart_CloseNativePort_DL(Dart_CloseNativePort_Type value) =>
      _Dart_CloseNativePort_DL.value = value;

  late final ffi.Pointer<Dart_IsError_Type> _Dart_IsError_DL =
      _lookup<Dart_IsError_Type>('Dart_IsError_DL');

  Dart_IsError_Type get Dart_IsError_DL => _Dart_IsError_DL.value;

  set Dart_IsError_DL(Dart_IsError_Type value) =>
      _Dart_IsError_DL.value = value;

  late final ffi.Pointer<Dart_IsApiError_Type> _Dart_IsApiError_DL =
      _lookup<Dart_IsApiError_Type>('Dart_IsApiError_DL');

  Dart_IsApiError_Type get Dart_IsApiError_DL => _Dart_IsApiError_DL.value;

  set Dart_IsApiError_DL(Dart_IsApiError_Type value) =>
      _Dart_IsApiError_DL.value = value;

  late final ffi.Pointer<Dart_IsUnhandledExceptionError_Type>
      _Dart_IsUnhandledExceptionError_DL =
      _lookup<Dart_IsUnhandledExceptionError_Type>(
          'Dart_IsUnhandledExceptionError_DL');

  Dart_IsUnhandledExceptionError_Type get Dart_IsUnhandledExceptionError_DL =>
      _Dart_IsUnhandledExceptionError_DL.value;

  set Dart_IsUnhandledExceptionError_DL(
          Dart_IsUnhandledExceptionError_Type value) =>
      _Dart_IsUnhandledExceptionError_DL.value = value;

  late final ffi.Pointer<Dart_IsCompilationError_Type>
      _Dart_IsCompilationError_DL =
      _lookup<Dart_IsCompilationError_Type>('Dart_IsCompilationError_DL');

  Dart_IsCompilationError_Type get Dart_IsCompilationError_DL =>
      _Dart_IsCompilationError_DL.value;

  set Dart_IsCompilationError_DL(Dart_IsCompilationError_Type value) =>
      _Dart_IsCompilationError_DL.value = value;

  late final ffi.Pointer<Dart_IsFatalError_Type> _Dart_IsFatalError_DL =
      _lookup<Dart_IsFatalError_Type>('Dart_IsFatalError_DL');

  Dart_IsFatalError_Type get Dart_IsFatalError_DL =>
      _Dart_IsFatalError_DL.value;

  set Dart_IsFatalError_DL(Dart_IsFatalError_Type value) =>
      _Dart_IsFatalError_DL.value = value;

  late final ffi.Pointer<Dart_GetError_Type> _Dart_GetError_DL =
      _lookup<Dart_GetError_Type>('Dart_GetError_DL');

  Dart_GetError_Type get Dart_GetError_DL => _Dart_GetError_DL.value;

  set Dart_GetError_DL(Dart_GetError_Type value) =>
      _Dart_GetError_DL.value = value;

  late final ffi.Pointer<Dart_ErrorHasException_Type>
      _Dart_ErrorHasException_DL =
      _lookup<Dart_ErrorHasException_Type>('Dart_ErrorHasException_DL');

  Dart_ErrorHasException_Type get Dart_ErrorHasException_DL =>
      _Dart_ErrorHasException_DL.value;

  set Dart_ErrorHasException_DL(Dart_ErrorHasException_Type value) =>
      _Dart_ErrorHasException_DL.value = value;

  late final ffi.Pointer<Dart_ErrorGetException_Type>
      _Dart_ErrorGetException_DL =
      _lookup<Dart_ErrorGetException_Type>('Dart_ErrorGetException_DL');

  Dart_ErrorGetException_Type get Dart_ErrorGetException_DL =>
      _Dart_ErrorGetException_DL.value;

  set Dart_ErrorGetException_DL(Dart_ErrorGetException_Type value) =>
      _Dart_ErrorGetException_DL.value = value;

  late final ffi.Pointer<Dart_ErrorGetStackTrace_Type>
      _Dart_ErrorGetStackTrace_DL =
      _lookup<Dart_ErrorGetStackTrace_Type>('Dart_ErrorGetStackTrace_DL');

  Dart_ErrorGetStackTrace_Type get Dart_ErrorGetStackTrace_DL =>
      _Dart_ErrorGetStackTrace_DL.value;

  set Dart_ErrorGetStackTrace_DL(Dart_ErrorGetStackTrace_Type value) =>
      _Dart_ErrorGetStackTrace_DL.value = value;

  late final ffi.Pointer<Dart_NewApiError_Type> _Dart_NewApiError_DL =
      _lookup<Dart_NewApiError_Type>('Dart_NewApiError_DL');

  Dart_NewApiError_Type get Dart_NewApiError_DL => _Dart_NewApiError_DL.value;

  set Dart_NewApiError_DL(Dart_NewApiError_Type value) =>
      _Dart_NewApiError_DL.value = value;

  late final ffi.Pointer<Dart_NewCompilationError_Type>
      _Dart_NewCompilationError_DL =
      _lookup<Dart_NewCompilationError_Type>('Dart_NewCompilationError_DL');

  Dart_NewCompilationError_Type get Dart_NewCompilationError_DL =>
      _Dart_NewCompilationError_DL.value;

  set Dart_NewCompilationError_DL(Dart_NewCompilationError_Type value) =>
      _Dart_NewCompilationError_DL.value = value;

  late final ffi.Pointer<Dart_NewUnhandledExceptionError_Type>
      _Dart_NewUnhandledExceptionError_DL =
      _lookup<Dart_NewUnhandledExceptionError_Type>(
          'Dart_NewUnhandledExceptionError_DL');

  Dart_NewUnhandledExceptionError_Type get Dart_NewUnhandledExceptionError_DL =>
      _Dart_NewUnhandledExceptionError_DL.value;

  set Dart_NewUnhandledExceptionError_DL(
          Dart_NewUnhandledExceptionError_Type value) =>
      _Dart_NewUnhandledExceptionError_DL.value = value;

  late final ffi.Pointer<Dart_PropagateError_Type> _Dart_PropagateError_DL =
      _lookup<Dart_PropagateError_Type>('Dart_PropagateError_DL');

  Dart_PropagateError_Type get Dart_PropagateError_DL =>
      _Dart_PropagateError_DL.value;

  set Dart_PropagateError_DL(Dart_PropagateError_Type value) =>
      _Dart_PropagateError_DL.value = value;

  late final ffi.Pointer<Dart_HandleFromPersistent_Type>
      _Dart_HandleFromPersistent_DL =
      _lookup<Dart_HandleFromPersistent_Type>('Dart_HandleFromPersistent_DL');

  Dart_HandleFromPersistent_Type get Dart_HandleFromPersistent_DL =>
      _Dart_HandleFromPersistent_DL.value;

  set Dart_HandleFromPersistent_DL(Dart_HandleFromPersistent_Type value) =>
      _Dart_HandleFromPersistent_DL.value = value;

  late final ffi.Pointer<Dart_HandleFromWeakPersistent_Type>
      _Dart_HandleFromWeakPersistent_DL =
      _lookup<Dart_HandleFromWeakPersistent_Type>(
          'Dart_HandleFromWeakPersistent_DL');

  Dart_HandleFromWeakPersistent_Type get Dart_HandleFromWeakPersistent_DL =>
      _Dart_HandleFromWeakPersistent_DL.value;

  set Dart_HandleFromWeakPersistent_DL(
          Dart_HandleFromWeakPersistent_Type value) =>
      _Dart_HandleFromWeakPersistent_DL.value = value;

  late final ffi.Pointer<Dart_NewPersistentHandle_Type>
      _Dart_NewPersistentHandle_DL =
      _lookup<Dart_NewPersistentHandle_Type>('Dart_NewPersistentHandle_DL');

  Dart_NewPersistentHandle_Type get Dart_NewPersistentHandle_DL =>
      _Dart_NewPersistentHandle_DL.value;

  set Dart_NewPersistentHandle_DL(Dart_NewPersistentHandle_Type value) =>
      _Dart_NewPersistentHandle_DL.value = value;

  late final ffi.Pointer<Dart_SetPersistentHandle_Type>
      _Dart_SetPersistentHandle_DL =
      _lookup<Dart_SetPersistentHandle_Type>('Dart_SetPersistentHandle_DL');

  Dart_SetPersistentHandle_Type get Dart_SetPersistentHandle_DL =>
      _Dart_SetPersistentHandle_DL.value;

  set Dart_SetPersistentHandle_DL(Dart_SetPersistentHandle_Type value) =>
      _Dart_SetPersistentHandle_DL.value = value;

  late final ffi.Pointer<Dart_DeletePersistentHandle_Type>
      _Dart_DeletePersistentHandle_DL =
      _lookup<Dart_DeletePersistentHandle_Type>(
          'Dart_DeletePersistentHandle_DL');

  Dart_DeletePersistentHandle_Type get Dart_DeletePersistentHandle_DL =>
      _Dart_DeletePersistentHandle_DL.value;

  set Dart_DeletePersistentHandle_DL(Dart_DeletePersistentHandle_Type value) =>
      _Dart_DeletePersistentHandle_DL.value = value;

  late final ffi.Pointer<Dart_NewWeakPersistentHandle_Type>
      _Dart_NewWeakPersistentHandle_DL =
      _lookup<Dart_NewWeakPersistentHandle_Type>(
          'Dart_NewWeakPersistentHandle_DL');

  Dart_NewWeakPersistentHandle_Type get Dart_NewWeakPersistentHandle_DL =>
      _Dart_NewWeakPersistentHandle_DL.value;

  set Dart_NewWeakPersistentHandle_DL(
          Dart_NewWeakPersistentHandle_Type value) =>
      _Dart_NewWeakPersistentHandle_DL.value = value;

  late final ffi.Pointer<Dart_DeleteWeakPersistentHandle_Type>
      _Dart_DeleteWeakPersistentHandle_DL =
      _lookup<Dart_DeleteWeakPersistentHandle_Type>(
          'Dart_DeleteWeakPersistentHandle_DL');

  Dart_DeleteWeakPersistentHandle_Type get Dart_DeleteWeakPersistentHandle_DL =>
      _Dart_DeleteWeakPersistentHandle_DL.value;

  set Dart_DeleteWeakPersistentHandle_DL(
          Dart_DeleteWeakPersistentHandle_Type value) =>
      _Dart_DeleteWeakPersistentHandle_DL.value = value;

  late final ffi.Pointer<Dart_NewFinalizableHandle_Type>
      _Dart_NewFinalizableHandle_DL =
      _lookup<Dart_NewFinalizableHandle_Type>('Dart_NewFinalizableHandle_DL');

  Dart_NewFinalizableHandle_Type get Dart_NewFinalizableHandle_DL =>
      _Dart_NewFinalizableHandle_DL.value;

  set Dart_NewFinalizableHandle_DL(Dart_NewFinalizableHandle_Type value) =>
      _Dart_NewFinalizableHandle_DL.value = value;

  late final ffi.Pointer<Dart_DeleteFinalizableHandle_Type>
      _Dart_DeleteFinalizableHandle_DL =
      _lookup<Dart_DeleteFinalizableHandle_Type>(
          'Dart_DeleteFinalizableHandle_DL');

  Dart_DeleteFinalizableHandle_Type get Dart_DeleteFinalizableHandle_DL =>
      _Dart_DeleteFinalizableHandle_DL.value;

  set Dart_DeleteFinalizableHandle_DL(
          Dart_DeleteFinalizableHandle_Type value) =>
      _Dart_DeleteFinalizableHandle_DL.value = value;

  late final ffi.Pointer<Dart_CurrentIsolate_Type> _Dart_CurrentIsolate_DL =
      _lookup<Dart_CurrentIsolate_Type>('Dart_CurrentIsolate_DL');

  Dart_CurrentIsolate_Type get Dart_CurrentIsolate_DL =>
      _Dart_CurrentIsolate_DL.value;

  set Dart_CurrentIsolate_DL(Dart_CurrentIsolate_Type value) =>
      _Dart_CurrentIsolate_DL.value = value;

  late final ffi.Pointer<Dart_ExitIsolate_Type> _Dart_ExitIsolate_DL =
      _lookup<Dart_ExitIsolate_Type>('Dart_ExitIsolate_DL');

  Dart_ExitIsolate_Type get Dart_ExitIsolate_DL => _Dart_ExitIsolate_DL.value;

  set Dart_ExitIsolate_DL(Dart_ExitIsolate_Type value) =>
      _Dart_ExitIsolate_DL.value = value;

  late final ffi.Pointer<Dart_EnterIsolate_Type> _Dart_EnterIsolate_DL =
      _lookup<Dart_EnterIsolate_Type>('Dart_EnterIsolate_DL');

  Dart_EnterIsolate_Type get Dart_EnterIsolate_DL =>
      _Dart_EnterIsolate_DL.value;

  set Dart_EnterIsolate_DL(Dart_EnterIsolate_Type value) =>
      _Dart_EnterIsolate_DL.value = value;

  late final ffi.Pointer<Dart_Post_Type> _Dart_Post_DL =
      _lookup<Dart_Post_Type>('Dart_Post_DL');

  Dart_Post_Type get Dart_Post_DL => _Dart_Post_DL.value;

  set Dart_Post_DL(Dart_Post_Type value) => _Dart_Post_DL.value = value;

  late final ffi.Pointer<Dart_NewSendPort_Type> _Dart_NewSendPort_DL =
      _lookup<Dart_NewSendPort_Type>('Dart_NewSendPort_DL');

  Dart_NewSendPort_Type get Dart_NewSendPort_DL => _Dart_NewSendPort_DL.value;

  set Dart_NewSendPort_DL(Dart_NewSendPort_Type value) =>
      _Dart_NewSendPort_DL.value = value;

  late final ffi.Pointer<Dart_SendPortGetId_Type> _Dart_SendPortGetId_DL =
      _lookup<Dart_SendPortGetId_Type>('Dart_SendPortGetId_DL');

  Dart_SendPortGetId_Type get Dart_SendPortGetId_DL =>
      _Dart_SendPortGetId_DL.value;

  set Dart_SendPortGetId_DL(Dart_SendPortGetId_Type value) =>
      _Dart_SendPortGetId_DL.value = value;

  late final ffi.Pointer<Dart_EnterScope_Type> _Dart_EnterScope_DL =
      _lookup<Dart_EnterScope_Type>('Dart_EnterScope_DL');

  Dart_EnterScope_Type get Dart_EnterScope_DL => _Dart_EnterScope_DL.value;

  set Dart_EnterScope_DL(Dart_EnterScope_Type value) =>
      _Dart_EnterScope_DL.value = value;

  late final ffi.Pointer<Dart_ExitScope_Type> _Dart_ExitScope_DL =
      _lookup<Dart_ExitScope_Type>('Dart_ExitScope_DL');

  Dart_ExitScope_Type get Dart_ExitScope_DL => _Dart_ExitScope_DL.value;

  set Dart_ExitScope_DL(Dart_ExitScope_Type value) =>
      _Dart_ExitScope_DL.value = value;

  late final ffi.Pointer<Dart_IsNull_Type> _Dart_IsNull_DL =
      _lookup<Dart_IsNull_Type>('Dart_IsNull_DL');

  Dart_IsNull_Type get Dart_IsNull_DL => _Dart_IsNull_DL.value;

  set Dart_IsNull_DL(Dart_IsNull_Type value) => _Dart_IsNull_DL.value = value;

  late final ffi.Pointer<Dart_UpdateExternalSize_Type>
      _Dart_UpdateExternalSize_DL =
      _lookup<Dart_UpdateExternalSize_Type>('Dart_UpdateExternalSize_DL');

  Dart_UpdateExternalSize_Type get Dart_UpdateExternalSize_DL =>
      _Dart_UpdateExternalSize_DL.value;

  set Dart_UpdateExternalSize_DL(Dart_UpdateExternalSize_Type value) =>
      _Dart_UpdateExternalSize_DL.value = value;

  late final ffi.Pointer<Dart_UpdateFinalizableExternalSize_Type>
      _Dart_UpdateFinalizableExternalSize_DL =
      _lookup<Dart_UpdateFinalizableExternalSize_Type>(
          'Dart_UpdateFinalizableExternalSize_DL');

  Dart_UpdateFinalizableExternalSize_Type
      get Dart_UpdateFinalizableExternalSize_DL =>
          _Dart_UpdateFinalizableExternalSize_DL.value;

  set Dart_UpdateFinalizableExternalSize_DL(
          Dart_UpdateFinalizableExternalSize_Type value) =>
      _Dart_UpdateFinalizableExternalSize_DL.value = value;

  /// World.
  ffi.Pointer<World> create_world() {
    return _create_world();
  }

  late final _create_worldPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<World> Function()>>(
          'create_world');
  late final _create_world =
      _create_worldPtr.asFunction<ffi.Pointer<World> Function()>();

  /// NOTE: There is only one instance of a BodyConfig available right now.
  ffi.Pointer<BodyConfig> world_get_body_config(
    ffi.Pointer<World> world,
  ) {
    return _world_get_body_config(
      world,
    );
  }

  late final _world_get_body_configPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<BodyConfig> Function(
              ffi.Pointer<World>)>>('world_get_body_config');
  late final _world_get_body_config = _world_get_body_configPtr
      .asFunction<ffi.Pointer<BodyConfig> Function(ffi.Pointer<World>)>();

  ffi.Pointer<WorldBody> world_create_body(
    ffi.Pointer<World> world,
    ffi.Pointer<BodyConfig> conifg,
  ) {
    return _world_create_body(
      world,
      conifg,
    );
  }

  late final _world_create_bodyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<WorldBody> Function(ffi.Pointer<World>,
              ffi.Pointer<BodyConfig>)>>('world_create_body');
  late final _world_create_body = _world_create_bodyPtr.asFunction<
      ffi.Pointer<WorldBody> Function(
          ffi.Pointer<World>, ffi.Pointer<BodyConfig>)>();

  void world_add_body(
    ffi.Pointer<World> world,
    ffi.Pointer<WorldBody> body,
    int activation,
  ) {
    return _world_add_body(
      world,
      body,
      activation,
    );
  }

  late final _world_add_bodyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<World>, ffi.Pointer<WorldBody>,
              ffi.Int)>>('world_add_body');
  late final _world_add_body = _world_add_bodyPtr.asFunction<
      void Function(ffi.Pointer<World>, ffi.Pointer<WorldBody>, int)>();

  void world_remove_body(
    ffi.Pointer<World> world,
    ffi.Pointer<WorldBody> body,
  ) {
    return _world_remove_body(
      world,
      body,
    );
  }

  late final _world_remove_bodyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<World>,
              ffi.Pointer<WorldBody>)>>('world_remove_body');
  late final _world_remove_body = _world_remove_bodyPtr
      .asFunction<void Function(ffi.Pointer<World>, ffi.Pointer<WorldBody>)>();

  int world_step(
    ffi.Pointer<World> world,
    double dt,
  ) {
    return _world_step(
      world,
      dt,
    );
  }

  late final _world_stepPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<World>, ffi.Float)>>(
      'world_step');
  late final _world_step =
      _world_stepPtr.asFunction<int Function(ffi.Pointer<World>, double)>();

  void destroy_world(
    ffi.Pointer<World> world,
  ) {
    return _destroy_world(
      world,
    );
  }

  late final _destroy_worldPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<World>)>>(
          'destroy_world');
  late final _destroy_world =
      _destroy_worldPtr.asFunction<void Function(ffi.Pointer<World>)>();

  /// NOTE: There is only one instance of a ConvexShapeConfig available right now.
  ffi.Pointer<ConvexShapeConfig> get_convex_shape_config() {
    return _get_convex_shape_config();
  }

  late final _get_convex_shape_configPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ConvexShapeConfig> Function()>>(
          'get_convex_shape_config');
  late final _get_convex_shape_config = _get_convex_shape_configPtr
      .asFunction<ffi.Pointer<ConvexShapeConfig> Function()>();

  ffi.Pointer<CollisionShape> create_convex_shape(
    ffi.Pointer<ConvexShapeConfig> config,
    ffi.Pointer<ffi.Float> points,
    int num_points,
  ) {
    return _create_convex_shape(
      config,
      points,
      num_points,
    );
  }

  late final _create_convex_shapePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<CollisionShape> Function(ffi.Pointer<ConvexShapeConfig>,
              ffi.Pointer<ffi.Float>, ffi.Int)>>('create_convex_shape');
  late final _create_convex_shape = _create_convex_shapePtr.asFunction<
      ffi.Pointer<CollisionShape> Function(ffi.Pointer<ConvexShapeConfig>,
          ffi.Pointer<ffi.Float>, int)>(isLeaf: true);

  /// NOTE: There is only one instance of a CompoundShapeConfig available right now.
  ffi.Pointer<CompoundShapeConfig> get_compound_shape_config() {
    return _get_compound_shape_config();
  }

  late final _get_compound_shape_configPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<CompoundShapeConfig> Function()>>(
          'get_compound_shape_config');
  late final _get_compound_shape_config = _get_compound_shape_configPtr
      .asFunction<ffi.Pointer<CompoundShapeConfig> Function()>();

  ffi.Pointer<CollisionShape> create_compound_shape(
    ffi.Pointer<CompoundShapeConfig> config,
  ) {
    return _create_compound_shape(
      config,
    );
  }

  late final _create_compound_shapePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<CollisionShape> Function(
              ffi.Pointer<CompoundShapeConfig>)>>('create_compound_shape');
  late final _create_compound_shape = _create_compound_shapePtr.asFunction<
      ffi.Pointer<CollisionShape> Function(ffi.Pointer<CompoundShapeConfig>)>();

  ffi.Pointer<CollisionShape> create_mesh_shape(
    ffi.Pointer<ffi.Float> vertices,
    int num_vertices,
    ffi.Pointer<ffi.Uint32> triangles,
    int num_triangles,
  ) {
    return _create_mesh_shape(
      vertices,
      num_vertices,
      triangles,
      num_triangles,
    );
  }

  late final _create_mesh_shapePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<CollisionShape> Function(ffi.Pointer<ffi.Float>, ffi.Int,
              ffi.Pointer<ffi.Uint32>, ffi.Int)>>('create_mesh_shape');
  late final _create_mesh_shape = _create_mesh_shapePtr.asFunction<
      ffi.Pointer<CollisionShape> Function(
          ffi.Pointer<ffi.Float>, int, ffi.Pointer<ffi.Uint32>, int)>();

  void shape_get_center_of_mass(
    ffi.Pointer<CollisionShape> shape,
    ffi.Pointer<ffi.Float> v3,
  ) {
    return _shape_get_center_of_mass(
      shape,
      v3,
    );
  }

  late final _shape_get_center_of_massPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CollisionShape>,
              ffi.Pointer<ffi.Float>)>>('shape_get_center_of_mass');
  late final _shape_get_center_of_mass =
      _shape_get_center_of_massPtr.asFunction<
          void Function(ffi.Pointer<CollisionShape>, ffi.Pointer<ffi.Float>)>();

  void shape_get_local_bounds(
    ffi.Pointer<CollisionShape> shape,
    ffi.Pointer<ffi.Float> min3,
    ffi.Pointer<ffi.Float> max3,
  ) {
    return _shape_get_local_bounds(
      shape,
      min3,
      max3,
    );
  }

  late final _shape_get_local_boundsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CollisionShape>, ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>)>>('shape_get_local_bounds');
  late final _shape_get_local_bounds = _shape_get_local_boundsPtr.asFunction<
      void Function(ffi.Pointer<CollisionShape>, ffi.Pointer<ffi.Float>,
          ffi.Pointer<ffi.Float>)>();

  void shape_set_dart_owner(
    ffi.Pointer<CollisionShape> shape,
    Object owner,
  ) {
    return _shape_set_dart_owner(
      shape,
      owner,
    );
  }

  late final _shape_set_dart_ownerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CollisionShape>,
              ffi.Handle)>>('shape_set_dart_owner');
  late final _shape_set_dart_owner = _shape_set_dart_ownerPtr
      .asFunction<void Function(ffi.Pointer<CollisionShape>, Object)>();

  Object shape_get_dart_owner(
    ffi.Pointer<CollisionShape> shape,
  ) {
    return _shape_get_dart_owner(
      shape,
    );
  }

  late final _shape_get_dart_ownerPtr = _lookup<
          ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<CollisionShape>)>>(
      'shape_get_dart_owner');
  late final _shape_get_dart_owner = _shape_get_dart_ownerPtr
      .asFunction<Object Function(ffi.Pointer<CollisionShape>)>();

  void destroy_shape(
    ffi.Pointer<CollisionShape> shape,
  ) {
    return _destroy_shape(
      shape,
    );
  }

  late final _destroy_shapePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CollisionShape>)>>(
      'destroy_shape');
  late final _destroy_shape = _destroy_shapePtr
      .asFunction<void Function(ffi.Pointer<CollisionShape>)>();

  /// Bodies.
  void body_set_position(
    ffi.Pointer<WorldBody> body,
    ffi.Pointer<ffi.Float> v4,
  ) {
    return _body_set_position(
      body,
      v4,
    );
  }

  late final _body_set_positionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<WorldBody>,
              ffi.Pointer<ffi.Float>)>>('body_set_position');
  late final _body_set_position = _body_set_positionPtr.asFunction<
      void Function(
          ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>(isLeaf: true);

  void body_set_rotation(
    ffi.Pointer<WorldBody> body,
    ffi.Pointer<ffi.Float> q4,
  ) {
    return _body_set_rotation(
      body,
      q4,
    );
  }

  late final _body_set_rotationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<WorldBody>,
              ffi.Pointer<ffi.Float>)>>('body_set_rotation');
  late final _body_set_rotation = _body_set_rotationPtr.asFunction<
      void Function(
          ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>(isLeaf: true);

  void body_get_position(
    ffi.Pointer<WorldBody> body,
    ffi.Pointer<ffi.Float> v4,
  ) {
    return _body_get_position(
      body,
      v4,
    );
  }

  late final _body_get_positionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<WorldBody>,
              ffi.Pointer<ffi.Float>)>>('body_get_position');
  late final _body_get_position = _body_get_positionPtr.asFunction<
      void Function(
          ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>(isLeaf: true);

  void body_get_rotation(
    ffi.Pointer<WorldBody> body,
    ffi.Pointer<ffi.Float> q4,
  ) {
    return _body_get_rotation(
      body,
      q4,
    );
  }

  late final _body_get_rotationPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<WorldBody>,
              ffi.Pointer<ffi.Float>)>>('body_get_rotation');
  late final _body_get_rotation = _body_get_rotationPtr.asFunction<
      void Function(
          ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>(isLeaf: true);

  void body_get_world_matrix(
    ffi.Pointer<WorldBody> body,
    ffi.Pointer<ffi.Float> m16,
  ) {
    return _body_get_world_matrix(
      body,
      m16,
    );
  }

  late final _body_get_world_matrixPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<WorldBody>,
              ffi.Pointer<ffi.Float>)>>('body_get_world_matrix');
  late final _body_get_world_matrix = _body_get_world_matrixPtr.asFunction<
      void Function(
          ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>(isLeaf: true);

  void body_get_com_matrix(
    ffi.Pointer<WorldBody> body,
    ffi.Pointer<ffi.Float> m16,
  ) {
    return _body_get_com_matrix(
      body,
      m16,
    );
  }

  late final _body_get_com_matrixPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<WorldBody>,
              ffi.Pointer<ffi.Float>)>>('body_get_com_matrix');
  late final _body_get_com_matrix = _body_get_com_matrixPtr.asFunction<
      void Function(
          ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>(isLeaf: true);

  void body_set_active(
    ffi.Pointer<WorldBody> body,
    bool activate,
  ) {
    return _body_set_active(
      body,
      activate,
    );
  }

  late final _body_set_activePtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<WorldBody>, ffi.Bool)>>(
      'body_set_active');
  late final _body_set_active = _body_set_activePtr
      .asFunction<void Function(ffi.Pointer<WorldBody>, bool)>(isLeaf: true);

  bool body_get_active(
    ffi.Pointer<WorldBody> body,
  ) {
    return _body_get_active(
      body,
    );
  }

  late final _body_get_activePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<WorldBody>)>>(
          'body_get_active');
  late final _body_get_active = _body_get_activePtr
      .asFunction<bool Function(ffi.Pointer<WorldBody>)>(isLeaf: true);

  void set_body_dart_owner(
    ffi.Pointer<WorldBody> body,
    Object owner,
  ) {
    return _set_body_dart_owner(
      body,
      owner,
    );
  }

  late final _set_body_dart_ownerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<WorldBody>, ffi.Handle)>>('set_body_dart_owner');
  late final _set_body_dart_owner = _set_body_dart_ownerPtr
      .asFunction<void Function(ffi.Pointer<WorldBody>, Object)>();

  Object get_body_dart_owner(
    ffi.Pointer<WorldBody> body,
  ) {
    return _get_body_dart_owner(
      body,
    );
  }

  late final _get_body_dart_ownerPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<WorldBody>)>>(
          'get_body_dart_owner');
  late final _get_body_dart_owner = _get_body_dart_ownerPtr
      .asFunction<Object Function(ffi.Pointer<WorldBody>)>();

  void destroy_body(
    ffi.Pointer<WorldBody> body,
  ) {
    return _destroy_body(
      body,
    );
  }

  late final _destroy_bodyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<WorldBody>)>>(
          'destroy_body');
  late final _destroy_body =
      _destroy_bodyPtr.asFunction<void Function(ffi.Pointer<WorldBody>)>();

  late final addresses = _SymbolAddresses(this);
}

class _SymbolAddresses {
  final Jolt _library;
  _SymbolAddresses(this._library);
  ffi.Pointer<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>
      get Dart_InitializeApiDL => _library._Dart_InitializeApiDLPtr;
  ffi.Pointer<Dart_PostCObject_Type> get Dart_PostCObject_DL =>
      _library._Dart_PostCObject_DL;
  ffi.Pointer<Dart_PostInteger_Type> get Dart_PostInteger_DL =>
      _library._Dart_PostInteger_DL;
  ffi.Pointer<Dart_NewNativePort_Type> get Dart_NewNativePort_DL =>
      _library._Dart_NewNativePort_DL;
  ffi.Pointer<Dart_CloseNativePort_Type> get Dart_CloseNativePort_DL =>
      _library._Dart_CloseNativePort_DL;
  ffi.Pointer<Dart_IsError_Type> get Dart_IsError_DL =>
      _library._Dart_IsError_DL;
  ffi.Pointer<Dart_IsApiError_Type> get Dart_IsApiError_DL =>
      _library._Dart_IsApiError_DL;
  ffi.Pointer<Dart_IsUnhandledExceptionError_Type>
      get Dart_IsUnhandledExceptionError_DL =>
          _library._Dart_IsUnhandledExceptionError_DL;
  ffi.Pointer<Dart_IsCompilationError_Type> get Dart_IsCompilationError_DL =>
      _library._Dart_IsCompilationError_DL;
  ffi.Pointer<Dart_IsFatalError_Type> get Dart_IsFatalError_DL =>
      _library._Dart_IsFatalError_DL;
  ffi.Pointer<Dart_GetError_Type> get Dart_GetError_DL =>
      _library._Dart_GetError_DL;
  ffi.Pointer<Dart_ErrorHasException_Type> get Dart_ErrorHasException_DL =>
      _library._Dart_ErrorHasException_DL;
  ffi.Pointer<Dart_ErrorGetException_Type> get Dart_ErrorGetException_DL =>
      _library._Dart_ErrorGetException_DL;
  ffi.Pointer<Dart_ErrorGetStackTrace_Type> get Dart_ErrorGetStackTrace_DL =>
      _library._Dart_ErrorGetStackTrace_DL;
  ffi.Pointer<Dart_NewApiError_Type> get Dart_NewApiError_DL =>
      _library._Dart_NewApiError_DL;
  ffi.Pointer<Dart_NewCompilationError_Type> get Dart_NewCompilationError_DL =>
      _library._Dart_NewCompilationError_DL;
  ffi.Pointer<Dart_NewUnhandledExceptionError_Type>
      get Dart_NewUnhandledExceptionError_DL =>
          _library._Dart_NewUnhandledExceptionError_DL;
  ffi.Pointer<Dart_PropagateError_Type> get Dart_PropagateError_DL =>
      _library._Dart_PropagateError_DL;
  ffi.Pointer<Dart_HandleFromPersistent_Type>
      get Dart_HandleFromPersistent_DL =>
          _library._Dart_HandleFromPersistent_DL;
  ffi.Pointer<Dart_HandleFromWeakPersistent_Type>
      get Dart_HandleFromWeakPersistent_DL =>
          _library._Dart_HandleFromWeakPersistent_DL;
  ffi.Pointer<Dart_NewPersistentHandle_Type> get Dart_NewPersistentHandle_DL =>
      _library._Dart_NewPersistentHandle_DL;
  ffi.Pointer<Dart_SetPersistentHandle_Type> get Dart_SetPersistentHandle_DL =>
      _library._Dart_SetPersistentHandle_DL;
  ffi.Pointer<Dart_DeletePersistentHandle_Type>
      get Dart_DeletePersistentHandle_DL =>
          _library._Dart_DeletePersistentHandle_DL;
  ffi.Pointer<Dart_NewWeakPersistentHandle_Type>
      get Dart_NewWeakPersistentHandle_DL =>
          _library._Dart_NewWeakPersistentHandle_DL;
  ffi.Pointer<Dart_DeleteWeakPersistentHandle_Type>
      get Dart_DeleteWeakPersistentHandle_DL =>
          _library._Dart_DeleteWeakPersistentHandle_DL;
  ffi.Pointer<Dart_NewFinalizableHandle_Type>
      get Dart_NewFinalizableHandle_DL =>
          _library._Dart_NewFinalizableHandle_DL;
  ffi.Pointer<Dart_DeleteFinalizableHandle_Type>
      get Dart_DeleteFinalizableHandle_DL =>
          _library._Dart_DeleteFinalizableHandle_DL;
  ffi.Pointer<Dart_CurrentIsolate_Type> get Dart_CurrentIsolate_DL =>
      _library._Dart_CurrentIsolate_DL;
  ffi.Pointer<Dart_ExitIsolate_Type> get Dart_ExitIsolate_DL =>
      _library._Dart_ExitIsolate_DL;
  ffi.Pointer<Dart_EnterIsolate_Type> get Dart_EnterIsolate_DL =>
      _library._Dart_EnterIsolate_DL;
  ffi.Pointer<Dart_Post_Type> get Dart_Post_DL => _library._Dart_Post_DL;
  ffi.Pointer<Dart_NewSendPort_Type> get Dart_NewSendPort_DL =>
      _library._Dart_NewSendPort_DL;
  ffi.Pointer<Dart_SendPortGetId_Type> get Dart_SendPortGetId_DL =>
      _library._Dart_SendPortGetId_DL;
  ffi.Pointer<Dart_EnterScope_Type> get Dart_EnterScope_DL =>
      _library._Dart_EnterScope_DL;
  ffi.Pointer<Dart_ExitScope_Type> get Dart_ExitScope_DL =>
      _library._Dart_ExitScope_DL;
  ffi.Pointer<Dart_IsNull_Type> get Dart_IsNull_DL => _library._Dart_IsNull_DL;
  ffi.Pointer<Dart_UpdateExternalSize_Type> get Dart_UpdateExternalSize_DL =>
      _library._Dart_UpdateExternalSize_DL;
  ffi.Pointer<Dart_UpdateFinalizableExternalSize_Type>
      get Dart_UpdateFinalizableExternalSize_DL =>
          _library._Dart_UpdateFinalizableExternalSize_DL;
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<World> Function()>>
      get create_world => _library._create_worldPtr;
  ffi.Pointer<
          ffi
          .NativeFunction<ffi.Pointer<BodyConfig> Function(ffi.Pointer<World>)>>
      get world_get_body_config => _library._world_get_body_configPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Pointer<WorldBody> Function(
                  ffi.Pointer<World>, ffi.Pointer<BodyConfig>)>>
      get world_create_body => _library._world_create_bodyPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<World>, ffi.Pointer<WorldBody>, ffi.Int)>>
      get world_add_body => _library._world_add_bodyPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<World>, ffi.Pointer<WorldBody>)>>
      get world_remove_body => _library._world_remove_bodyPtr;
  ffi.Pointer<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<World>, ffi.Float)>>
      get world_step => _library._world_stepPtr;
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<World>)>>
      get destroy_world => _library._destroy_worldPtr;
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ConvexShapeConfig> Function()>>
      get get_convex_shape_config => _library._get_convex_shape_configPtr;
  ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<CollisionShape> Function(
              ffi.Pointer<ConvexShapeConfig>,
              ffi.Pointer<ffi.Float>,
              ffi.Int)>> get create_convex_shape =>
      _library._create_convex_shapePtr;
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<CompoundShapeConfig> Function()>>
      get get_compound_shape_config => _library._get_compound_shape_configPtr;
  ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<CollisionShape> Function(
              ffi.Pointer<CompoundShapeConfig>)>> get create_compound_shape =>
      _library._create_compound_shapePtr;
  ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<CollisionShape> Function(
              ffi.Pointer<ffi.Float>,
              ffi.Int,
              ffi.Pointer<ffi.Uint32>,
              ffi.Int)>> get create_mesh_shape =>
      _library._create_mesh_shapePtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<CollisionShape>, ffi.Pointer<ffi.Float>)>>
      get shape_get_center_of_mass => _library._shape_get_center_of_massPtr;
  ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<CollisionShape>, ffi.Pointer<ffi.Float>,
              ffi.Pointer<ffi.Float>)>> get shape_get_local_bounds =>
      _library._shape_get_local_boundsPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<CollisionShape>, ffi.Handle)>>
      get shape_set_dart_owner => _library._shape_set_dart_ownerPtr;
  ffi.Pointer<
          ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<CollisionShape>)>>
      get shape_get_dart_owner => _library._shape_get_dart_ownerPtr;
  ffi.Pointer<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<CollisionShape>)>>
      get destroy_shape => _library._destroy_shapePtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>>
      get body_set_position => _library._body_set_positionPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>>
      get body_set_rotation => _library._body_set_rotationPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>>
      get body_get_position => _library._body_get_positionPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>>
      get body_get_rotation => _library._body_get_rotationPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>>
      get body_get_world_matrix => _library._body_get_world_matrixPtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<WorldBody>, ffi.Pointer<ffi.Float>)>>
      get body_get_com_matrix => _library._body_get_com_matrixPtr;
  ffi.Pointer<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<WorldBody>, ffi.Bool)>>
      get body_set_active => _library._body_set_activePtr;
  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<WorldBody>)>>
      get body_get_active => _library._body_get_activePtr;
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<WorldBody>, ffi.Handle)>>
      get set_body_dart_owner => _library._set_body_dart_ownerPtr;
  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<WorldBody>)>>
      get get_body_dart_owner => _library._get_body_dart_ownerPtr;
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<WorldBody>)>>
      get destroy_body => _library._destroy_bodyPtr;
}

typedef Dart_PostCObject_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_PostCObject_TypeFunction>>;
typedef Dart_PostCObject_TypeFunction = ffi.Bool Function(
    Dart_Port_DL port_id, ffi.Pointer<Dart_CObject> message);
typedef DartDart_PostCObject_TypeFunction = bool Function(
    DartDart_Port_DL port_id, ffi.Pointer<Dart_CObject> message);

/// ============================================================================
/// IMPORTANT! Never update these signatures without properly updating
/// DART_API_DL_MAJOR_VERSION and DART_API_DL_MINOR_VERSION.
///
/// Verbatim copy of `dart_native_api.h` and `dart_api.h` symbol names and types
/// to trigger compile-time errors if the symbols in those files are updated
/// without updating these.
///
/// Function return and argument types, and typedefs are carbon copied. Structs
/// are typechecked nominally in C/C++, so they are not copied, instead a
/// comment is added to their definition.
typedef Dart_Port_DL = ffi.Int64;
typedef DartDart_Port_DL = int;

/// This enum is versioned by DART_API_DL_MAJOR_VERSION, only add at the end
/// and bump the DART_API_DL_MINOR_VERSION.
typedef Dart_CObject = _Dart_CObject;

/// This enum is versioned by DART_API_DL_MAJOR_VERSION, only add at the end
/// and bump the DART_API_DL_MINOR_VERSION.
final class _Dart_CObject extends ffi.Struct {
  @ffi.Int32()
  external int type;

  external UnnamedUnion1 value;
}

/// A Dart_CObject is used for representing Dart objects as native C
/// data outside the Dart heap. These objects are totally detached from
/// the Dart heap. Only a subset of the Dart objects have a
/// representation as a Dart_CObject.
///
/// The string encoding in the 'value.as_string' is UTF-8.
///
/// All the different types from dart:typed_data are exposed as type
/// kTypedData. The specific type from dart:typed_data is in the type
/// field of the as_typed_data structure. The length in the
/// as_typed_data structure is always in bytes.
///
/// The data for kTypedData is copied on message send and ownership remains with
/// the caller. The ownership of data for kExternalTyped is passed to the VM on
/// message send and returned when the VM invokes the
/// Dart_HandleFinalizer callback; a non-NULL callback must be provided.
///
/// Note that Dart_CObject_kNativePointer is intended for internal use by
/// dart:io implementation and has no connection to dart:ffi Pointer class.
/// It represents a pointer to a native resource of a known type.
/// The receiving side will only see this pointer as an integer and will not
/// see the specified finalizer.
/// The specified finalizer will only be invoked if the message is not delivered.
abstract class Dart_CObject_Type {
  static const int Dart_CObject_kNull = 0;
  static const int Dart_CObject_kBool = 1;
  static const int Dart_CObject_kInt32 = 2;
  static const int Dart_CObject_kInt64 = 3;
  static const int Dart_CObject_kDouble = 4;
  static const int Dart_CObject_kString = 5;
  static const int Dart_CObject_kArray = 6;
  static const int Dart_CObject_kTypedData = 7;
  static const int Dart_CObject_kExternalTypedData = 8;
  static const int Dart_CObject_kSendPort = 9;
  static const int Dart_CObject_kCapability = 10;
  static const int Dart_CObject_kNativePointer = 11;
  static const int Dart_CObject_kUnsupported = 12;
  static const int Dart_CObject_kUnmodifiableExternalTypedData = 13;
  static const int Dart_CObject_kNumberOfTypes = 14;
}

final class UnnamedUnion1 extends ffi.Union {
  @ffi.Bool()
  external bool as_bool;

  @ffi.Int32()
  external int as_int32;

  @ffi.Int64()
  external int as_int64;

  @ffi.Double()
  external double as_double;

  external ffi.Pointer<ffi.Char> as_string;

  external UnnamedStruct1 as_send_port;

  external UnnamedStruct2 as_capability;

  external UnnamedStruct3 as_array;

  external UnnamedStruct4 as_typed_data;

  external UnnamedStruct5 as_external_typed_data;

  external UnnamedStruct6 as_native_pointer;
}

final class UnnamedStruct1 extends ffi.Struct {
  @Dart_Port()
  external int id;

  @Dart_Port()
  external int origin_id;
}

/// A port is used to send or receive inter-isolate messages
typedef Dart_Port = ffi.Int64;
typedef DartDart_Port = int;

final class UnnamedStruct2 extends ffi.Struct {
  @ffi.Int64()
  external int id;
}

final class UnnamedStruct3 extends ffi.Struct {
  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Pointer<_Dart_CObject>> values;
}

final class UnnamedStruct4 extends ffi.Struct {
  @ffi.Int32()
  external int type;

  /// in elements, not bytes
  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> values;
}

/// ==========
/// Typed Data
/// ==========
abstract class Dart_TypedData_Type {
  static const int Dart_TypedData_kByteData = 0;
  static const int Dart_TypedData_kInt8 = 1;
  static const int Dart_TypedData_kUint8 = 2;
  static const int Dart_TypedData_kUint8Clamped = 3;
  static const int Dart_TypedData_kInt16 = 4;
  static const int Dart_TypedData_kUint16 = 5;
  static const int Dart_TypedData_kInt32 = 6;
  static const int Dart_TypedData_kUint32 = 7;
  static const int Dart_TypedData_kInt64 = 8;
  static const int Dart_TypedData_kUint64 = 9;
  static const int Dart_TypedData_kFloat32 = 10;
  static const int Dart_TypedData_kFloat64 = 11;
  static const int Dart_TypedData_kInt32x4 = 12;
  static const int Dart_TypedData_kFloat32x4 = 13;
  static const int Dart_TypedData_kFloat64x2 = 14;
  static const int Dart_TypedData_kInvalid = 15;
}

final class UnnamedStruct5 extends ffi.Struct {
  @ffi.Int32()
  external int type;

  /// in elements, not bytes
  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> data;

  external ffi.Pointer<ffi.Void> peer;

  external Dart_HandleFinalizer callback;
}

/// These structs are versioned by DART_API_DL_MAJOR_VERSION, bump the
/// version when changing this struct.
typedef Dart_HandleFinalizer
    = ffi.Pointer<ffi.NativeFunction<Dart_HandleFinalizerFunction>>;
typedef Dart_HandleFinalizerFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> isolate_callback_data, ffi.Pointer<ffi.Void> peer);
typedef DartDart_HandleFinalizerFunction = void Function(
    ffi.Pointer<ffi.Void> isolate_callback_data, ffi.Pointer<ffi.Void> peer);

final class UnnamedStruct6 extends ffi.Struct {
  @ffi.IntPtr()
  external int ptr;

  @ffi.IntPtr()
  external int size;

  external Dart_HandleFinalizer callback;
}

typedef Dart_PostInteger_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_PostInteger_TypeFunction>>;
typedef Dart_PostInteger_TypeFunction = ffi.Bool Function(
    Dart_Port_DL port_id, ffi.Int64 message);
typedef DartDart_PostInteger_TypeFunction = bool Function(
    DartDart_Port_DL port_id, int message);
typedef Dart_NewNativePort_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_NewNativePort_TypeFunction>>;
typedef Dart_NewNativePort_TypeFunction = Dart_Port_DL Function(
    ffi.Pointer<ffi.Char> name,
    Dart_NativeMessageHandler_DL handler,
    ffi.Bool handle_concurrently);
typedef DartDart_NewNativePort_TypeFunction = DartDart_Port_DL Function(
    ffi.Pointer<ffi.Char> name,
    Dart_NativeMessageHandler_DL handler,
    bool handle_concurrently);
typedef Dart_NativeMessageHandler_DL
    = ffi.Pointer<ffi.NativeFunction<Dart_NativeMessageHandler_DLFunction>>;
typedef Dart_NativeMessageHandler_DLFunction = ffi.Void Function(
    Dart_Port_DL dest_port_id, ffi.Pointer<Dart_CObject> message);
typedef DartDart_NativeMessageHandler_DLFunction = void Function(
    DartDart_Port_DL dest_port_id, ffi.Pointer<Dart_CObject> message);
typedef Dart_CloseNativePort_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_CloseNativePort_TypeFunction>>;
typedef Dart_CloseNativePort_TypeFunction = ffi.Bool Function(
    Dart_Port_DL native_port_id);
typedef DartDart_CloseNativePort_TypeFunction = bool Function(
    DartDart_Port_DL native_port_id);
typedef Dart_IsError_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_IsError_TypeFunction>>;
typedef Dart_IsError_TypeFunction = ffi.Bool Function(ffi.Handle handle);
typedef DartDart_IsError_TypeFunction = bool Function(Object handle);
typedef Dart_IsApiError_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_IsApiError_TypeFunction>>;
typedef Dart_IsApiError_TypeFunction = ffi.Bool Function(ffi.Handle handle);
typedef DartDart_IsApiError_TypeFunction = bool Function(Object handle);
typedef Dart_IsUnhandledExceptionError_Type = ffi
    .Pointer<ffi.NativeFunction<Dart_IsUnhandledExceptionError_TypeFunction>>;
typedef Dart_IsUnhandledExceptionError_TypeFunction = ffi.Bool Function(
    ffi.Handle handle);
typedef DartDart_IsUnhandledExceptionError_TypeFunction = bool Function(
    Object handle);
typedef Dart_IsCompilationError_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_IsCompilationError_TypeFunction>>;
typedef Dart_IsCompilationError_TypeFunction = ffi.Bool Function(
    ffi.Handle handle);
typedef DartDart_IsCompilationError_TypeFunction = bool Function(Object handle);
typedef Dart_IsFatalError_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_IsFatalError_TypeFunction>>;
typedef Dart_IsFatalError_TypeFunction = ffi.Bool Function(ffi.Handle handle);
typedef DartDart_IsFatalError_TypeFunction = bool Function(Object handle);
typedef Dart_GetError_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_GetError_TypeFunction>>;
typedef Dart_GetError_TypeFunction = ffi.Pointer<ffi.Char> Function(
    ffi.Handle handle);
typedef DartDart_GetError_TypeFunction = ffi.Pointer<ffi.Char> Function(
    Object handle);
typedef Dart_ErrorHasException_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_ErrorHasException_TypeFunction>>;
typedef Dart_ErrorHasException_TypeFunction = ffi.Bool Function(
    ffi.Handle handle);
typedef DartDart_ErrorHasException_TypeFunction = bool Function(Object handle);
typedef Dart_ErrorGetException_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_ErrorGetException_TypeFunction>>;
typedef Dart_ErrorGetException_TypeFunction = ffi.Handle Function(
    ffi.Handle handle);
typedef DartDart_ErrorGetException_TypeFunction = Object Function(
    Object handle);
typedef Dart_ErrorGetStackTrace_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_ErrorGetStackTrace_TypeFunction>>;
typedef Dart_ErrorGetStackTrace_TypeFunction = ffi.Handle Function(
    ffi.Handle handle);
typedef DartDart_ErrorGetStackTrace_TypeFunction = Object Function(
    Object handle);
typedef Dart_NewApiError_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_NewApiError_TypeFunction>>;
typedef Dart_NewApiError_TypeFunction = ffi.Handle Function(
    ffi.Pointer<ffi.Char> error);
typedef DartDart_NewApiError_TypeFunction = Object Function(
    ffi.Pointer<ffi.Char> error);
typedef Dart_NewCompilationError_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_NewCompilationError_TypeFunction>>;
typedef Dart_NewCompilationError_TypeFunction = ffi.Handle Function(
    ffi.Pointer<ffi.Char> error);
typedef DartDart_NewCompilationError_TypeFunction = Object Function(
    ffi.Pointer<ffi.Char> error);
typedef Dart_NewUnhandledExceptionError_Type = ffi
    .Pointer<ffi.NativeFunction<Dart_NewUnhandledExceptionError_TypeFunction>>;
typedef Dart_NewUnhandledExceptionError_TypeFunction = ffi.Handle Function(
    ffi.Handle exception);
typedef DartDart_NewUnhandledExceptionError_TypeFunction = Object Function(
    Object exception);
typedef Dart_PropagateError_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_PropagateError_TypeFunction>>;
typedef Dart_PropagateError_TypeFunction = ffi.Void Function(ffi.Handle handle);
typedef DartDart_PropagateError_TypeFunction = void Function(Object handle);
typedef Dart_HandleFromPersistent_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_HandleFromPersistent_TypeFunction>>;
typedef Dart_HandleFromPersistent_TypeFunction = ffi.Handle Function(
    ffi.Handle object);
typedef DartDart_HandleFromPersistent_TypeFunction = Object Function(
    Object object);
typedef Dart_HandleFromWeakPersistent_Type = ffi
    .Pointer<ffi.NativeFunction<Dart_HandleFromWeakPersistent_TypeFunction>>;
typedef Dart_HandleFromWeakPersistent_TypeFunction = ffi.Handle Function(
    Dart_WeakPersistentHandle object);
typedef DartDart_HandleFromWeakPersistent_TypeFunction = Object Function(
    Dart_WeakPersistentHandle object);
typedef Dart_WeakPersistentHandle = ffi.Pointer<_Dart_WeakPersistentHandle>;

final class _Dart_WeakPersistentHandle extends ffi.Opaque {}

typedef Dart_NewPersistentHandle_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_NewPersistentHandle_TypeFunction>>;
typedef Dart_NewPersistentHandle_TypeFunction = ffi.Handle Function(
    ffi.Handle object);
typedef DartDart_NewPersistentHandle_TypeFunction = Object Function(
    Object object);
typedef Dart_SetPersistentHandle_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_SetPersistentHandle_TypeFunction>>;
typedef Dart_SetPersistentHandle_TypeFunction = ffi.Void Function(
    ffi.Handle obj1, ffi.Handle obj2);
typedef DartDart_SetPersistentHandle_TypeFunction = void Function(
    Object obj1, Object obj2);
typedef Dart_DeletePersistentHandle_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_DeletePersistentHandle_TypeFunction>>;
typedef Dart_DeletePersistentHandle_TypeFunction = ffi.Void Function(
    ffi.Handle object);
typedef DartDart_DeletePersistentHandle_TypeFunction = void Function(
    Object object);
typedef Dart_NewWeakPersistentHandle_Type = ffi
    .Pointer<ffi.NativeFunction<Dart_NewWeakPersistentHandle_TypeFunction>>;
typedef Dart_NewWeakPersistentHandle_TypeFunction
    = Dart_WeakPersistentHandle Function(
        ffi.Handle object,
        ffi.Pointer<ffi.Void> peer,
        ffi.IntPtr external_allocation_size,
        Dart_HandleFinalizer callback);
typedef DartDart_NewWeakPersistentHandle_TypeFunction
    = Dart_WeakPersistentHandle Function(
        Object object,
        ffi.Pointer<ffi.Void> peer,
        int external_allocation_size,
        Dart_HandleFinalizer callback);
typedef Dart_DeleteWeakPersistentHandle_Type = ffi
    .Pointer<ffi.NativeFunction<Dart_DeleteWeakPersistentHandle_TypeFunction>>;
typedef Dart_DeleteWeakPersistentHandle_TypeFunction = ffi.Void Function(
    Dart_WeakPersistentHandle object);
typedef DartDart_DeleteWeakPersistentHandle_TypeFunction = void Function(
    Dart_WeakPersistentHandle object);
typedef Dart_NewFinalizableHandle_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_NewFinalizableHandle_TypeFunction>>;
typedef Dart_NewFinalizableHandle_TypeFunction
    = Dart_FinalizableHandle Function(
        ffi.Handle object,
        ffi.Pointer<ffi.Void> peer,
        ffi.IntPtr external_allocation_size,
        Dart_HandleFinalizer callback);
typedef DartDart_NewFinalizableHandle_TypeFunction
    = Dart_FinalizableHandle Function(Object object, ffi.Pointer<ffi.Void> peer,
        int external_allocation_size, Dart_HandleFinalizer callback);
typedef Dart_FinalizableHandle = ffi.Pointer<_Dart_FinalizableHandle>;

final class _Dart_FinalizableHandle extends ffi.Opaque {}

typedef Dart_DeleteFinalizableHandle_Type = ffi
    .Pointer<ffi.NativeFunction<Dart_DeleteFinalizableHandle_TypeFunction>>;
typedef Dart_DeleteFinalizableHandle_TypeFunction = ffi.Void Function(
    Dart_FinalizableHandle object, ffi.Handle strong_ref_to_object);
typedef DartDart_DeleteFinalizableHandle_TypeFunction = void Function(
    Dart_FinalizableHandle object, Object strong_ref_to_object);
typedef Dart_CurrentIsolate_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_CurrentIsolate_TypeFunction>>;
typedef Dart_CurrentIsolate_TypeFunction = Dart_Isolate Function();

/// An isolate is the unit of concurrency in Dart. Each isolate has
/// its own memory and thread of control. No state is shared between
/// isolates. Instead, isolates communicate by message passing.
///
/// Each thread keeps track of its current isolate, which is the
/// isolate which is ready to execute on the current thread. The
/// current isolate may be NULL, in which case no isolate is ready to
/// execute. Most of the Dart apis require there to be a current
/// isolate in order to function without error. The current isolate is
/// set by any call to Dart_CreateIsolateGroup or Dart_EnterIsolate.
typedef Dart_Isolate = ffi.Pointer<_Dart_Isolate>;

final class _Dart_Isolate extends ffi.Opaque {}

typedef Dart_ExitIsolate_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_ExitIsolate_TypeFunction>>;
typedef Dart_ExitIsolate_TypeFunction = ffi.Void Function();
typedef DartDart_ExitIsolate_TypeFunction = void Function();
typedef Dart_EnterIsolate_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_EnterIsolate_TypeFunction>>;
typedef Dart_EnterIsolate_TypeFunction = ffi.Void Function(Dart_Isolate);
typedef DartDart_EnterIsolate_TypeFunction = void Function(Dart_Isolate);
typedef Dart_Post_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_Post_TypeFunction>>;
typedef Dart_Post_TypeFunction = ffi.Bool Function(
    Dart_Port_DL port_id, ffi.Handle object);
typedef DartDart_Post_TypeFunction = bool Function(
    DartDart_Port_DL port_id, Object object);
typedef Dart_NewSendPort_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_NewSendPort_TypeFunction>>;
typedef Dart_NewSendPort_TypeFunction = ffi.Handle Function(
    Dart_Port_DL port_id);
typedef DartDart_NewSendPort_TypeFunction = Object Function(
    DartDart_Port_DL port_id);
typedef Dart_SendPortGetId_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_SendPortGetId_TypeFunction>>;
typedef Dart_SendPortGetId_TypeFunction = ffi.Handle Function(
    ffi.Handle port, ffi.Pointer<Dart_Port_DL> port_id);
typedef DartDart_SendPortGetId_TypeFunction = Object Function(
    Object port, ffi.Pointer<Dart_Port_DL> port_id);
typedef Dart_EnterScope_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_EnterScope_TypeFunction>>;
typedef Dart_EnterScope_TypeFunction = ffi.Void Function();
typedef DartDart_EnterScope_TypeFunction = void Function();
typedef Dart_ExitScope_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_ExitScope_TypeFunction>>;
typedef Dart_ExitScope_TypeFunction = ffi.Void Function();
typedef DartDart_ExitScope_TypeFunction = void Function();
typedef Dart_IsNull_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_IsNull_TypeFunction>>;
typedef Dart_IsNull_TypeFunction = ffi.Bool Function(ffi.Handle);
typedef DartDart_IsNull_TypeFunction = bool Function(Object);
typedef Dart_UpdateExternalSize_Type
    = ffi.Pointer<ffi.NativeFunction<Dart_UpdateExternalSize_TypeFunction>>;
typedef Dart_UpdateExternalSize_TypeFunction = ffi.Void Function(
    Dart_WeakPersistentHandle object, ffi.IntPtr external_allocation_size);
typedef DartDart_UpdateExternalSize_TypeFunction = void Function(
    Dart_WeakPersistentHandle object, int external_allocation_size);
typedef Dart_UpdateFinalizableExternalSize_Type = ffi.Pointer<
    ffi.NativeFunction<Dart_UpdateFinalizableExternalSize_TypeFunction>>;
typedef Dart_UpdateFinalizableExternalSize_TypeFunction = ffi.Void Function(
    Dart_FinalizableHandle object,
    ffi.Handle strong_ref_to_object,
    ffi.IntPtr external_allocation_size);
typedef DartDart_UpdateFinalizableExternalSize_TypeFunction = void Function(
    Dart_FinalizableHandle object,
    Object strong_ref_to_object,
    int external_allocation_size);

final class World extends ffi.Opaque {}

final class CollisionShape extends ffi.Opaque {}

final class WorldBody extends ffi.Opaque {}

/// Configuration for a body when it si created.
final class BodyConfig extends ffi.Struct {
  external ffi.Pointer<CollisionShape> shape;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> position;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> rotation;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> linear_velocity;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> angular_velocity;

  @ffi.Int()
  external int motion_type;

  @ffi.Int()
  external int motion_quality;
}

abstract class ConvexShapeConfigType {
  static const int kUnknown = 0;
  static const int kBox = 1;
  static const int kSphere = 2;
  static const int kCapsule = 3;
  static const int kConvexHull = 4;
}

final class ConvexShapeConfig extends ffi.Struct {
  @ffi.Int32()
  external int type;

  @ffi.Float()
  external double density;

  /// kBox:
  /// payload is the half extents.
  /// kSphere:
  /// payload[0] is the radius.
  /// kCapsule:
  /// payload[0] is half height, payload[1] is top radius, payload[2] is bottom radius.
  /// kConvexHull:
  /// payload is not used.
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Float> payload;
}

final class CompoundShapeConfig extends ffi.Struct {
  /// TODO(johnmccutchan): Don't artificially limit the number of compound shapes we can pass.
  @ffi.Array.multi([16])
  external ffi.Array<PerShape> shapes;

  @ffi.Int()
  external int num_shapes;
}

final class PerShape extends ffi.Struct {
  external ffi.Pointer<CollisionShape> shape;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Float> position;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Float> rotation;
}
